-- ============================================================================
-- SAMPLE DATA - Insert this into Neon SQL Editor
-- ============================================================================

-- Insert default settings
INSERT INTO settings (shop_name, owner_name, shop_phone, shop_address, tax_rate, currency, low_stock_default_threshold)
VALUES ('FrostyFlow', 'Owner', '', '', 0, 'INR', 50)
ON CONFLICT DO NOTHING;

-- Insert sample products (IDs will be generated by Neon)
INSERT INTO products (name, brand, category, created_at, updated_at) VALUES
('Coca-Cola Classic', 'The Coca-Cola Company', 'Sodas', NOW(), NOW()),
('Pepsi Blue', 'PepsiCo', 'Sodas', NOW(), NOW()),
('Sprite', 'The Coca-Cola Company', 'Sodas', NOW(), NOW()),
('Red Bull Energy', 'Red Bull GmbH', 'Energy Drinks', NOW(), NOW()),
('Mountain Dew', 'PepsiCo', 'Energy Drinks', NOW(), NOW()),
('Orange Juice', 'Citrus Farms', 'Juices', NOW(), NOW()),
('Mineral Water', 'Alpine Springs', 'Water', NOW(), NOW()),
('Nestle Water', 'Nestle', 'Water', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert product sizes (first get products then insert sizes)
INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '500ml', '35', '350', 12, NOW()
FROM products p WHERE p.name = 'Coca-Cola Classic'
ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '1L', '50', '500', 12, NOW()
FROM products p WHERE p.name = 'Sprite'
ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '250ml', '150', '1200', 24, NOW()
FROM products p WHERE p.name = 'Red Bull Energy'
ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '500ml', '45', '450', 12, NOW()
FROM products p WHERE p.name = 'Mountain Dew'
ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '1L', '80', '800', 12, NOW()
FROM products p WHERE p.name = 'Orange Juice'
ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '1L', '20', '200', 24, NOW()
FROM products p WHERE p.name = 'Mineral Water'
ON CONFLICT DO NOTHING;

INSERT INTO product_sizes (product_id, size_name, price_per_bottle, price_per_carton, bottles_per_carton, created_at)
SELECT p.id, '1L', '18', '180', 24, NOW()
FROM products p WHERE p.name = 'Nestle Water'
ON CONFLICT DO NOTHING;

-- Insert sample inventory
INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'COC-COL-500ML-' || substring(md5(random()::text) from 1 for 3), 100, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Coca-Cola Classic' AND ps.size_name = '500ml'
ON CONFLICT DO NOTHING;

INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'COC-SPR-1L-' || substring(md5(random()::text) from 1 for 3), 80, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Sprite' AND ps.size_name = '1L'
ON CONFLICT DO NOTHING;

INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'RED-BUL-250ML-' || substring(md5(random()::text) from 1 for 3), 40, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Red Bull Energy' AND ps.size_name = '250ml'
ON CONFLICT DO NOTHING;

INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'PEP-MTD-500ML-' || substring(md5(random()::text) from 1 for 3), 60, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Mountain Dew' AND ps.size_name = '500ml'
ON CONFLICT DO NOTHING;

INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'CIT-ORA-1L-' || substring(md5(random()::text) from 1 for 3), 35, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Orange Juice' AND ps.size_name = '1L'
ON CONFLICT DO NOTHING;

INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'ALP-MIN-1L-' || substring(md5(random()::text) from 1 for 3), 200, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Mineral Water' AND ps.size_name = '1L'
ON CONFLICT DO NOTHING;

INSERT INTO inventory (product_size_id, sku_code, current_stock, low_stock_threshold, status, created_at, updated_at)
SELECT ps.id, 'NES-WAT-1L-' || substring(md5(random()::text) from 1 for 3), 150, 50, 'Healthy', NOW(), NOW()
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE p.name = 'Nestle Water' AND ps.size_name = '1L'
ON CONFLICT DO NOTHING;

-- Insert invoice counter
INSERT INTO invoice_counter (id, last_number) VALUES (1, 0)
ON CONFLICT (id) DO UPDATE SET last_number = 0;

-- Verify data
SELECT 'Products' as table_name, COUNT(*) as count FROM products
UNION ALL
SELECT 'Product Sizes', COUNT(*) FROM product_sizes
UNION ALL
SELECT 'Inventory', COUNT(*) FROM inventory
UNION ALL
SELECT 'Settings', COUNT(*) FROM settings;
